name: FibBot
description: A GitHub Action to calculate Fibonacci numbers from the pull request content.

inputs:
  enable_fib:
    description: 'Enable Fibonacci calculation'
    required: true
    default: 'true'
  max_threshold:
    description: 'Maximum value for Fibonacci calculation'
    required: false
    default: '100o'

runs:
  using: 'docker'
  image: 'Dockerfile'
